const ERROR_CODES = {
    VALIDATION: {
        MISSING_CREDENTIALS: "MISSING_CREDENTIALS",
        INVALID_INPUT: "INVALID_INPUT",
        INVALID_DATE: "INVALID_DATE",
        INVALID_WEEK_FILTER: "INVALID_WEEK_FILTER",
        INVALID_TARGET_SESSIONS: "INVALID_TARGET_SESSIONS",
    },

    AUTHENTICATION: {
        INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    },

    AUTHORIZATION: {
        FORBIDDEN: "FORBIDDEN",
    },

    RESOURCE: {
        SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
        WEEKLY_GOAL_NOT_FOUND: "WEEKLY_GOAL_NOT_FOUND",
        WEEKLY_GOAL_ALREADY_EXISTS: "WEEKLY_GOAL_ALREADY_EXISTS",
        EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    },
};

module.exports = {
    ERROR_CODES,
};